### ISSUE TITLE
Age of Data character must not be "0" (Unknown)

### ISSUE THREAD

**Issue by timbellomo** [porcej/njord#17]
Client software ignores all PV sentences that are flagged with unknown age (0).  

I would propose that we derive the age based on the GPS Fix Time.  If age of fix time is less than a certain threshold, or if AP scan was used, send as "fresh" (2).  If fix time age is beyond the threshold, send in as "old" (1).

Normally, fresh is <10 seconds old, but we may need to account for leap seconds.

Ultimately, the client software doesn't care as much about the GPS Time of Day characters.  It looks to the Age of Data indicator to decide whether it will be disregarded.

**Comment by porcej** [comment]
If the GPS is in deferential or dead reconning mode, then the position could but valid and still have a gps fixtime > 10 seconds.

**Comment by timbellomo** [comment]
Honestly, I'm fine with "fresh" as long as the API is responding at all. The point is, we need to be publishing them as fresh at least some of the time.
