### ISSUE TITLE
Investigating the need for conversion of location.gnss.speed

### ISSUE THREAD

**Issue by timbellomo** [porcej/njord#30]
njord is reporting unrealistic speeds in its TAIP message, such as an engine traveling 108 MPH on the highway.  While possible, it's much more likely that location.gnss.speed reports KPH, and the engine was actually traveling ~67 MPH.

Need to confirm this issue and its fix.

**Comment by porcej** [comment]
Please provide real world location.gnss.speed samples.  Based on the Airlink AOS documentation, I believe this is the uncompensated, instantaneous speed which makes either value equally likely

**Comment by porcej** [comment]
Still waiting on documentation here. thanks

**Comment by timbellomo** [comment]
I received word after submitting a support ticket that the value is km per
hour.
