### ISSUE TITLE
Is it possible to suppress certificate warnings?

### ISSUE THREAD

**Issue by timbellomo** [porcej/njord#34]
These are spamming the log file.

` warnings.warn(
/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
`

**Comment by porcej** [comment]
please handle this at the interpreter level  ie passing python "-W ignore::InsecureRequestWarning"
