### ISSUE TITLE
datetime.datetime doesn't exist

### ISSUE THREAD

**Issue by timbellomo** [porcej/njord#4]
https://github.com/porcej/njord/blob/f2d9c38c44e0dea3862872eabe7636f790b2b3fe/njord.py#L86

https://github.com/porcej/njord/blob/f2d9c38c44e0dea3862872eabe7636f790b2b3fe/njord.py#L95
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'

**Comment by porcej** [comment]
Closed by 3A9bbf6
/

**Comment by porcej** [comment]
Closed by 3A9bbf6
