### ISSUE TITLE
Config URL must include protocol/scheme

### ISSUE THREAD

**Issue by timbellomo** [porcej/njord#5]
https://github.com/porcej/njord/blob/f2d9c38c44e0dea3862872eabe7636f790b2b3fe/README.md?plain=1#L31

Update readme to hint that protocol/scheme should be included in variable.

**Comment by porcej** [comment]
I'm not certain how to make this more clear as the URL contains the scheme, subdomain, secondary-level domain, top-level domain, subdirectory(s), and arguments.  What is being asked for is the URL and it seems pretty clear to me.

https://github.com/porcej/njord/blob/f2d9c38c44e0dea3862872eabe7636f790b2b3fe/README.md?plain=1#L31-L32

With that said, if you (or anyone) have a way to make this more clear, feel free to have a go.  If you do make changes, consider making them in the help parameters for --config_url in arg parser.

**Comment by timbellomo** [comment]
fair - i suppose it's clear enough.  URLs should always have their scheme, and that's implicit.
